name: Sivle-laget
favicon: null
layout_spectrum: 0.00903
typography_spectrum: 0.6243748681154102
title: Sivle-laget
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76455573-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbd1a1'
    - '#050402'
    - '#c2b5ac'
    - '#534528'
    - '#9d7a5c'
  brandStrength: 1
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
