name: Sivle-laget
favicon: null
layout_spectrum: 0.00903
typography_spectrum: 0.30649
title: Sivle-laget
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76455573-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#0097ff'
    - '#929292'
    - '#49eefe'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
