name: Sivle-laget
favicon: null
layout_spectrum: 0.25226
typography_spectrum: 0.6243748681154102
title: Sivle-laget
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76455573-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#d9d9d9'
    - '#9a9a9a'
    - '#555555'
    - '#171717'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.4375
  rhythmicContrast: 0.75
purpose: []
