name: Sivle-laget
favicon: null
layout_spectrum: 0.9225480945315212
typography_spectrum: 0.6243748681154102
title: Sivle-laget
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbd1a1'
    - '#050402'
    - '#c2b5ac'
    - '#534528'
    - '#9d7a5c'
  brandStrength: 0.7240492722485214
  lightness: 0.6995217334479094
  saturation: 0.34046294051222503
  rhythmicContrast: 0.5799025548622012
purpose: []
